public enum DegreeFaculty {
    SOFTWARE_ENGINEERING,
    ELECTRICAL_ENGINEERING,
    INFORMATION_TECHNOLOGY_ENGINEERING,
    BIOTECHNICAL_ENGINEERING,
    MECHANICAL_ENGINEERING,
    MANAGEMENT_ENGINEERING
}
